### ISSUE TITLE
MoM 1.3.6 causes invalid import

### ISSUE THREAD

**Issue by Roozbenz** [NPBruce/valkyrie#565]
after i press the reimport button everythings stop working the game ( mansion of madness ) wont open , what should i do ?

sry for my bad english xD

**Comment by NPBruce** [comment]
What version are you running?

Are you running Windows, Linux or MacOS?

When you press reimport do you see the Valkyrie logo?  Does it move?

After a while does it return to the main screen?

Why are you reimporting?

Please attach the log file (Valkyrie_data/player.log on Windows).

**Comment by Roozbenz** [comment]
latest version i think  Valkyrie 1.4.0a
Windows 10
yes , and yes its moving
yest it return to the main menu
i donno 1 just press it by accident 
i just remove the folder and re copy it so i dont have a player.log in that folder ps: re copy the valkyrie folder doesnt help me at all steel not working 
any suggestion ?

**Comment by NPBruce** [comment]
Firstly 1.4.0a is a prerelease, the current stable release is 1.3.0.  This can be found linked from the main page here:
https://github.com/NPBruce/valkyrie/wiki

You still shouldn't have this problem though.  Did it work before?  What happens when you press the MoM button?  Try again and get a log?

**Comment by Roozbenz** [comment]
still nothing , nothing happens after i click on MoM , mouse cursor changed to the green one ( i think MoM looks like this ) but nothing happend

**Comment by Roozbenz** [comment]
![image](https://user-images.githubusercontent.com/15629376/28103131-7653fcfa-66e9-11e7-98d6-7a5ac88fea0e.png)
somthing like this .

**Comment by NPBruce** [comment]
OK please attach the log.

**Comment by Roozbenz** [comment]
there is no log file sir am i missing somthing ?
![image](https://user-images.githubusercontent.com/15629376/28103198-c834a3bc-66e9-11e7-803d-8cc1315b7c2c.png)

**Comment by NPBruce** [comment]
output_log.txt, got the wrong name.

**Comment by Roozbenz** [comment]
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1140980/output_log.txt)
here

**Comment by NPBruce** [comment]
You have an invalid import, this log shows attempting to run MoM.  Can you please reimport and provide the log again to see why the import isn't working?

**Comment by Roozbenz** [comment]
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1140988/output_log.txt)
after reimporting ~~

**Comment by NPBruce** [comment]
I am not sure what is happening, try deleting C:\Users\Roozbenz\AppData\Roaming\Valkyrie\MoM\import and start again.

**Comment by Roozbenz** [comment]
still nothing
[output_log.txt](https://github.com/NPBruce/valkyrie/files/1141012/output_log.txt)
"after deleting the import folder and reimporting again"

**Comment by NPBruce** [comment]
Just realised you have MoM 1.3.6, which just come out today.  Good chance that broke Valkyrie.  I will look at this when I get a chance.

**Comment by Roozbenz** [comment]
okay im waiting for your reply , have a nice day

**Comment by Roozbenz** [comment]
any good news ?

**Comment by NPBruce** [comment]
Only bad news at the moment.  There is a static function definition:

public static Localization.LoadFunction loadFunction;

which is called to load the language text, but this is not set anywhere obvious in the managed code.  I need to work out what is doing this job.  Most likely FFG have done this on purpose to stop Valkyrie and/or prevent leaks of app text.

**Comment by LordPyrex** [comment]
Is this definitely done on the offensive? Or could they just be trying to compile the handler a little more effectively?

**Comment by NPBruce** [comment]
Still investigating, but I'd say 98% chance this is very deliberate.

**Comment by NPBruce** [comment]
If anyone has a copy of Mansions of Madness\Mansions of Madness_Data\Managed from 1.3.5 that would be very helpful.

**Comment by cbusbird** [comment]
I believe this is what you are looking for.  If not I probably have it on another PC.
[Managed.zip](https://github.com/NPBruce/valkyrie/files/1144031/Managed.zip)

**Comment by eorahil** [comment]
WOW. NPBruce you were right wanting to avoid using the original ffg texts and using only a valkyrie dictionaries.... T_T

**Comment by GamerXXX25** [comment]
Here is the whole 1.3.5, downloaded from Steam with helping of SteamDB:
[https://yadi.sk/d/BobyPoDB3KyHSg](Just click download)
Hope it helps.

**Comment by GamerXXX25** [comment]
Here is the whole 1.3.5, downloaded from Steam with helping of SteamDB:
[Just click download](https://yadi.sk/d/BobyPoDB3KyHSg)
Hope it helps.

**Comment by redwolf2** [comment]
`public static Localization.LoadFunction loadFunction;`
was already present in 1.3.5.

But the call `FFGTools.ObfuscateBytes` was removed in `LoadCSV`.

**Comment by NPBruce** [comment]
Yep, but given that the localization asset doesn't exist I assume they are using that delegate now. I am going to do code injection to see what is actually happening, but I am both sick and busy right now.

**Comment by redwolf2** [comment]
I could be wrong here, but I guess they could be in:

Mansions of Madness_Data\StreamingAssets\AssetBundles\1.3.6\Windows\localization

The folder contains:

- mad21
- mad21.manifest
- mad22
- mad22.manifest
- mad23
- mad23.manifest
- main
- main.manifest
- mad20
- mad20.manifest

main.manifest contains:

```
ManifestFileVersion: 0
CRC: 3598233751
Hashes:
  AssetFileHash:
    serializedVersion: 2
    Hash: ce6117afdce8f70efbb0da81a9b59c88
  TypeTreeHash:
    serializedVersion: 2
    Hash: 1033bf7ddfd4c6d43e7a6382c0a0a61a
HashAppended: 0
ClassTypes:
- Class: 49
  Script: {instanceID: 0}
Assets:
- Assets/Localization/Localization_ja.bytes
- Assets/Localization/Localization_pt.bytes
- Assets/Localization/Localization_pl.bytes
- Assets/Localization/Localization_zh.bytes
- Assets/Localization/Localization_en.bytes
- Assets/Localization/Localization_de.bytes
- Assets/Localization/Localization_it.bytes
- Assets/Localization/Localization_es.bytes
- Assets/Localization/Localization_fr.bytes
Dependencies: []

```
